const testCatalog = [
  {
    name: 'Oversized Casual Top',
    brand: 'Happyby',
    style: 'oversized_top',
    price: 1750,
    fabric: 'Cotton',
    sizes: 'S,M,L',
    colors: 'Black,White',
    stock: 12,
  },
  {
    name: 'Ribbed Crop Top',
    brand: 'Happyby',
    style: 'crop_top',
    price: 1250,
    fabric: 'Ribbed Cotton',
    sizes: 'S,M',
    colors: 'Beige,Pink',
    stock: 6,
  },
  {
    name: 'Breezy Summer Dress',
    brand: 'Happyby',
    style: 'summer_dress',
    price: 2950,
    fabric: 'Rayon',
    sizes: 'S,M,L',
    colors: 'Coral,Sage',
    stock: 9,
  },
  {
    name: 'Relaxed Linen Pants',
    brand: 'Happyby',
    style: 'linen_pants',
    price: 2400,
    fabric: 'Linen Blend',
    sizes: 'S,M,L',
    colors: 'Beige,Black',
    stock: 10,
  },
  {
    name: 'Pleated Midi Skirt',
    brand: 'Happyby',
    style: 'midi_skirt',
    price: 2100,
    fabric: 'Crepe',
    sizes: 'S,M,L',
    colors: 'Black,Cream',
    stock: 8,
  },
  {
    name: 'Premium Evening Gown',
    brand: 'Cleopatra',
    style: 'evening_gown',
    price: 8500,
    fabric: 'Silk',
    sizes: 'M,L',
    colors: 'Red,Navy',
    stock: 0,
  },
  {
    name: 'Satin Evening Top',
    brand: 'Cleopatra',
    style: 'evening_top',
    price: 3800,
    fabric: 'Satin',
    sizes: 'S,M,L',
    colors: 'Black,Champagne',
    stock: 7,
  },
  {
    name: 'Cocktail Midi Dress',
    brand: 'Cleopatra',
    style: 'cocktail_dress',
    price: 6200,
    fabric: 'Satin Blend',
    sizes: 'S,M,L',
    colors: 'Emerald,Black',
    stock: 5,
  },
  {
    name: 'Palazzo Pants',
    brand: 'Cleopatra',
    style: 'palazzo_pants',
    price: 4100,
    fabric: 'Soft Crepe',
    sizes: 'S,M,L',
    colors: 'Black,Navy',
    stock: 6,
  },
  {
    name: 'Mermaid Skirt',
    brand: 'Cleopatra',
    style: 'mermaid_skirt',
    price: 3600,
    fabric: 'Structured Knit',
    sizes: 'S,M,L',
    colors: 'Wine,Black',
    stock: 4,
  },
  {
    name: 'Classic Office Shirt',
    brand: 'Modabella',
    style: 'office_shirt',
    price: 3200,
    fabric: 'Linen',
    sizes: 'S,M,L,XL',
    colors: 'White,Blue',
    stock: 45,
  },
  {
    name: 'Tailored Work Dress',
    brand: 'Modabella',
    style: 'work_dress',
    price: 5400,
    fabric: 'Ponte',
    sizes: 'S,M,L,XL',
    colors: 'Navy,Charcoal',
    stock: 11,
  },
  {
    name: 'Straight Leg Trousers',
    brand: 'Modabella',
    style: 'tailored_pants',
    price: 4300,
    fabric: 'Suiting',
    sizes: 'S,M,L,XL',
    colors: 'Black,Charcoal',
    stock: 14,
  },
  {
    name: 'A-Line Skirt',
    brand: 'Modabella',
    style: 'a_line_skirt',
    price: 3500,
    fabric: 'Twill',
    sizes: 'S,M,L,XL',
    colors: 'Black,Stone',
    stock: 13,
  },
];

// Variant-level stock distribution per product.
// Keys are "brand:name", values are { size: { color: qty } }.
// Totals must match product.stock above.
const variantStocks = {
  'Happyby:Oversized Casual Top': {
    S: { Black: 2, White: 2 },
    M: { Black: 3, White: 2 },
    L: { Black: 2, White: 1 },
  },
  'Happyby:Ribbed Crop Top': {
    S: { Beige: 2, Pink: 1 },
    M: { Beige: 2, Pink: 1 },
  },
  'Happyby:Breezy Summer Dress': {
    S: { Coral: 2, Sage: 1 },
    M: { Coral: 2, Sage: 2 },
    L: { Coral: 1, Sage: 1 },
  },
  'Happyby:Relaxed Linen Pants': {
    S: { Beige: 2, Black: 1 },
    M: { Beige: 2, Black: 2 },
    L: { Beige: 2, Black: 1 },
  },
  'Happyby:Pleated Midi Skirt': {
    S: { Black: 1, Cream: 2 },
    M: { Black: 2, Cream: 1 },
    L: { Black: 1, Cream: 1 },
  },
  'Cleopatra:Premium Evening Gown': {
    M: { Red: 0, Navy: 0 },
    L: { Red: 0, Navy: 0 },
  },
  'Cleopatra:Satin Evening Top': {
    S: { Black: 1, Champagne: 1 },
    M: { Black: 2, Champagne: 1 },
    L: { Black: 1, Champagne: 1 },
  },
  'Cleopatra:Cocktail Midi Dress': {
    S: { Emerald: 1, Black: 1 },
    M: { Emerald: 1, Black: 1 },
    L: { Emerald: 1, Black: 0 },
  },
  'Cleopatra:Palazzo Pants': {
    S: { Black: 1, Navy: 1 },
    M: { Black: 2, Navy: 1 },
    L: { Black: 1, Navy: 0 },
  },
  'Cleopatra:Mermaid Skirt': {
    S: { Wine: 1, Black: 1 },
    M: { Wine: 1, Black: 1 },
    L: { Wine: 0, Black: 0 },
  },
  'Modabella:Classic Office Shirt': {
    S:  { White: 6, Blue: 6 },
    M:  { White: 7, Blue: 7 },
    L:  { White: 6, Blue: 6 },
    XL: { White: 4, Blue: 3 },
  },
  'Modabella:Tailored Work Dress': {
    S:  { Navy: 1, Charcoal: 2 },
    M:  { Navy: 2, Charcoal: 2 },
    L:  { Navy: 2, Charcoal: 1 },
    XL: { Navy: 1, Charcoal: 0 },
  },
  'Modabella:Straight Leg Trousers': {
    S:  { Black: 2, Charcoal: 2 },
    M:  { Black: 3, Charcoal: 2 },
    L:  { Black: 2, Charcoal: 2 },
    XL: { Black: 1, Charcoal: 0 },
  },
  'Modabella:A-Line Skirt': {
    S:  { Black: 2, Stone: 2 },
    M:  { Black: 2, Stone: 3 },
    L:  { Black: 2, Stone: 1 },
    XL: { Black: 1, Stone: 0 },
  },
};

module.exports = {
  testCatalog,
  variantStocks,
};
