const testCatalog = [
  {
    name: 'Oversized Casual Top',
    brand: 'Happyby',
    style: 'oversized_top',
    price: 1750,
    fabric: 'Cotton',
    sizes: 'S,M,L',
    colors: 'Black,White',
    stock: 12,
  },
  {
    name: 'Ribbed Crop Top',
    brand: 'Happyby',
    style: 'crop_top',
    price: 1250,
    fabric: 'Ribbed Cotton',
    sizes: 'S,M',
    colors: 'Beige,Pink',
    stock: 6,
  },
  {
    name: 'Breezy Summer Dress',
    brand: 'Happyby',
    style: 'summer_dress',
    price: 2950,
    fabric: 'Rayon',
    sizes: 'S,M,L',
    colors: 'Coral,Sage',
    stock: 9,
  },
  {
    name: 'Relaxed Linen Pants',
    brand: 'Happyby',
    style: 'linen_pants',
    price: 2400,
    fabric: 'Linen Blend',
    sizes: 'S,M,L',
    colors: 'Beige,Black',
    stock: 10,
  },
  {
    name: 'Pleated Midi Skirt',
    brand: 'Happyby',
    style: 'midi_skirt',
    price: 2100,
    fabric: 'Crepe',
    sizes: 'S,M,L',
    colors: 'Black,Cream',
    stock: 8,
  },
  {
    name: 'Premium Evening Gown',
    brand: 'Cleopatra',
    style: 'evening_gown',
    price: 8500,
    fabric: 'Silk',
    sizes: 'M,L',
    colors: 'Red,Navy',
    stock: 0,
  },
  {
    name: 'Satin Evening Top',
    brand: 'Cleopatra',
    style: 'evening_top',
    price: 3800,
    fabric: 'Satin',
    sizes: 'S,M,L',
    colors: 'Black,Champagne',
    stock: 7,
  },
  {
    name: 'Cocktail Midi Dress',
    brand: 'Cleopatra',
    style: 'cocktail_dress',
    price: 6200,
    fabric: 'Satin Blend',
    sizes: 'S,M,L',
    colors: 'Emerald,Black',
    stock: 5,
  },
  {
    name: 'Palazzo Pants',
    brand: 'Cleopatra',
    style: 'palazzo_pants',
    price: 4100,
    fabric: 'Soft Crepe',
    sizes: 'S,M,L',
    colors: 'Black,Navy',
    stock: 6,
  },
  {
    name: 'Mermaid Skirt',
    brand: 'Cleopatra',
    style: 'mermaid_skirt',
    price: 3600,
    fabric: 'Structured Knit',
    sizes: 'S,M,L',
    colors: 'Wine,Black',
    stock: 4,
  },
  {
    name: 'Classic Office Shirt',
    brand: 'Modabella',
    style: 'office_shirt',
    price: 3200,
    fabric: 'Linen',
    sizes: 'S,M,L,XL',
    colors: 'White,Blue',
    stock: 45,
  },
  {
    name: 'Tailored Work Dress',
    brand: 'Modabella',
    style: 'work_dress',
    price: 5400,
    fabric: 'Ponte',
    sizes: 'S,M,L,XL',
    colors: 'Navy,Charcoal',
    stock: 11,
  },
  {
    name: 'Straight Leg Trousers',
    brand: 'Modabella',
    style: 'tailored_pants',
    price: 4300,
    fabric: 'Suiting',
    sizes: 'S,M,L,XL',
    colors: 'Black,Charcoal',
    stock: 14,
  },
  {
    name: 'A-Line Skirt',
    brand: 'Modabella',
    style: 'a_line_skirt',
    price: 3500,
    fabric: 'Twill',
    sizes: 'S,M,L,XL',
    colors: 'Black,Stone',
    stock: 13,
  },
];

module.exports = {
  testCatalog,
};
